### ISSUE TITLE
Sync persisted data from ETCD to local sqlite on a Harbor instance startup

### ISSUE THREAD

**Issue by srm912** [vuil/harbor#29] opened 2017-03-16 03:19 UTC
Problem to solve: populate the local db store on first start or restart of the harbor instance

Poll ETCD for persisted data and create corresponding records in the Harbor local sqlite store.

**Comment by vuil** [comment] 2017-03-16 23:52
This is dupe of #3 which I closed

**Comment by vuil** [comment] 2017-03-22 17:59
we should keep this open since I closed the other

**Closed** 2017-06-23 17:45 UTC
